apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui
  annotations:
    backstage.io/kubernetes-id: guestbook
    backstage.io/techdocs-ref: guestbook
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: guestbook-ui
